# Introduction to Julia

Reference: This tutorial is based on a tutorial presented at the [JuMP-dev 2019](https://github.com/juan-pablo-vielma/JuMP-dev-2019-tutorial), and examples are adapted from the [Kamiński, Bogumił. 2023. Julia for Data Analysis. Manning.](https://github.com/bkamins/JuliaForDataAnalysis)

## Other Resources

This notebook is designed to provide a minimalist crash course in the basics of Julia. Other resources:
* [Intro to Julia](https://youtu.be/r2d5NA7RHno)  

* [“Learn X in Y Minutes”](https://learnxinyminutes.com/docs/julia/) 
* [From Zero to Julia!](https://techytok.com/from-zero-to-julia/) 

* [Julia Cheatsheet](https://cheatsheet.juliadocs.org/)
* [Cheatsheet of basic functions](https://cheatsheets.quantecon.org/julia-cheatsheet.html)
* [Plots Cheatsheet](https://github.com/sswatson/cheatsheets/blob/master/plotsjl-cheatsheet.pdf)

* [Cheatsheet for differences between Julia and Matlab and Python](https://cheatsheets.quantecon.org/)

* [Think Julia: How to Think Like a Computer Scientist](https://benlauwens.github.io/ThinkJulia.jl/latest/book.html#chap01)

* [Advanced Scientific Computing - Tim Holy](https://github.com/timholy/AdvancedScientificComputing/tree/main)

* [Official documentation](https://docs.julialang.org/en/v1/)



## Introduction

- Julia is a general purpose, multi-platform, (strongly) dynamically typed, high-performance, programming language well suited for **numerical analysis** and **computational science**.  

- Julia programs compile to efficient native code for multiple platforms via LLVM that allows it to match the performance of languages such as C and FORTRAN without the hassle of low-level code. 

- Because the code is compiled on the fly you can run code in a shell or REPL, which is part of the recommended workflow .

- Julia has a built-in package manager.

- Julia was created in 2012.

### Using the REPL
- Recall last result 	`ans`

- Interrupt execution 	`[Ctrl] + [C]`  

- Clear screen 	`[Ctrl] + [L]  `

- Run program 	`include("filename.jl")`  

- Package Manager mode 	`]` on empty line  

- Help mode 	`?` on empty line  

- Exit REPL 	`exit()` or `[Ctrl] + [D]` 

### Using Packages and the Package Manager

The Package Manager is used to install packages that are not part of Julia's standard library.

For example the following can be used to install JuMP,
```julia
using Pkg
Pkg.add("JuMP")
```

In [151]:
using Random
[rand() for i in 1:10]

10-element Vector{Float64}:
 0.5777380114136625
 0.6470426889546197
 0.05546299043159453
 0.004681112985528313
 0.0928497340411405
 0.21978318106147177
 0.7619240566076749
 0.17230398520738754
 0.43125831795824987
 0.014667241816034626


For a complete list of registed Julia packages see the package listing at https://pkg.julialang.org/.

From time to you may wish to use a Julia package that is not registered.  In this case a git repository URL can be used to install the package.
```julia
using Pkg
Pkg.add("https://github.com/user-name/MyPackage.jl.git")
```

#### USEFUL COMMANDS

- List installed packages (human-readable) 	`Pkg.status()`

- Update all packages 	`Pkg.update()`  

- Install PackageName 	`Pkg.add("PackageName")`  

- Rebuild PackageName 	`Pkg.build("PackageName") ` 

- Use PackageName (after install) 	`using PackageName`

- Remove PackageName 	`Pkg.rm("PackageName")`


In Interactive Package Mode

- Add PackageName 	`add PackageName`

- Remove PackageName 	`rm PackageName`

- Update PackageName 	`update PackageName`

#### HELP!

Julia 1.0 includes a help mode that can be accessed using `?`.  Entering any object (e.g. function, type, struct, ...) into the help mode will show its documentation, if any is available.




### Basic Data Types

Integers

In [8]:
1 + -2

-1

In [9]:
typeof(1)

Int64

Floating point numbers

In [10]:
1.2 - 2.3

-1.0999999999999999

In [11]:
typeof(-1.1)

Float64

There are also some cool things like an irrational representation of π. To make π (and most other greek letters), type \pi and then press [TAB].

In [29]:
π

π = 3.1415926535897...

julia allows Unicode names (in UTF-8 encoding) so either "pi" or the symbol π can be used

In [30]:
typeof(π)

Irrational{:π}

Julia has native support for complex numbers

In [31]:
2 + 3im

2 + 3im

In [32]:
typeof(2 + 3im)

Complex{Int64}

In [34]:
exp(A)

9.974182454814718

Double quotes are used for strings

In [35]:
"This is Julia"

"This is Julia"

In [36]:
typeof("This is Julia")

String

Unicode is fine in strings

In [37]:
"π is about 3.1415"

"π is about 3.1415"

Single quote for characters

In [38]:
'b'
typeof('b')

Char

String literals are encoded using the UTF-8 encoding:

In [39]:
σ = 2
𝒮 = 4   # \scrS  

4

In [40]:
😀 = 10
🥲 = -10
😀 + 🥲

0

### Printing 

In [41]:
println("I'm Julia. Nice to meet you!")  # => I'm Julia. Nice to meet you!

I'm Julia. Nice to meet you!


### Basic arithmetic

In [43]:
@show 2 + 10  # 12
@show 2^3     # 8
@show 3/12    # 0.25
@show 3//12
# Enforce precedence with parentheses
@show (1 + 3) * 2  # => 8

2 + 10 = 12
2 ^ 3 = 8
3 / 12 = 0.25
3 // 12 = 1//4
(1 + 3) * 2 = 8


8

Even math involving complex numbers

In [44]:
(2 + 1im) * (1 - 2im)

4 - 3im

### Logical operations 

In [95]:
@show a = b = 6   # assignment
@show !true       # false: negation
@show a == b      # equality
@show a != b      # inequality
@show a > b       # larger
@show a >= b      # greater than or equal to
@show a < b       # less  
@show a <= b ;    # less than or equal to

a = (b = 6) = 6
!true = false
a == b = true
a != b = false
a > b = false
a >= b = true
a < b = false
a <= b = true


Note, however that `==` implements exact numerical equality:

In [7]:
@show 2/3
@show 2//3
2/3 == 2//3

2 / 3 = 0.6666666666666666
2 // 3 = 2//3


false

### Vectors, Matrices and Arrays

Similar to Matlab, Julia has native support for vectors, matrices and tensors; all of which are represented by arrays of different dimensions.

Vectors are constructed by comma-separated elements surrounded by square brackets:

In [45]:
b = [5, 6]

2-element Vector{Int64}:
 5
 6

In [46]:
[1.0, 5.2, -2.1, 7]

4-element Vector{Float64}:
  1.0
  5.2
 -2.1
  7.0

In [99]:
a[1]  # => 1  # remember that Julia indexes from 1, not 0
# a[0]      # BoundsError
# end is a shorthand for the last index.
a[end]  # => 6

6

In [100]:
# You can initialize arrays from ranges
@show a1 = 1:5 ; # => UnitRange{Int64}: 1:5
@show a = [1:5;]  # => 5-element Array{Int64,1}: [1,2,3,4,5]

# You can look at ranges with slice syntax.
@show a[1:3]    # => [1, 2, 3]
@show a[2:end]  # => [2, 3, 4, 5] 

a1 = 1:5 = 1:5
a = [1:5;] = [1, 2, 3, 4, 5]
a[1:3] = [1, 2, 3]
a[2:end] = [2, 3, 4, 5]


4-element Vector{Int64}:
 2
 3
 4
 5

Matrices can be constructed with spaces separating the columns, and semicolons separating the rows:

In [101]:
A = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [106]:
# Arrays of a particular type
b = Int8[4, 5, 6] # => 3-element Array{Int8,1}: [4, 5, 6]

3-element Vector{Int8}:
 4
 5
 6

In [107]:
a = Int64[] # => 0-element Array{Int64,1}

# Add stuff to the end of a vector with push! and append!
# By convention, the exclamation mark '!' is appended to names of functions
# that modify their arguments
push!(a, 1)    # => [1]
push!(a, 2)    # => [1,2]
push!(a, 4)    # => [1,2,4]
push!(a, 3)    # => [1,2,4,3]
@show append!(a, b)  # => [1,2,4,3,4,5,6]
# Remove from the end with pop
pop!(b)  # => 6
b # => [4,5]

append!(a, b) = [1, 2, 4, 3, 4, 5, 6]


2-element Vector{Int8}:
 4
 5

In [108]:
a = [1,2,4,3,4,5,6]
# we also have popfirst! and pushfirst!
popfirst!(a)  # => 1 
a # => [2,4,3,4,5,6]

6-element Vector{Int64}:
 2
 4
 3
 4
 5
 6

In [109]:
@show pushfirst!(a, 7) 
@show a ;

pushfirst!(a, 7) = [7, 2, 4, 3, 4, 5, 6]
a = [7, 2, 4, 3, 4, 5, 6]


In [110]:
# Function names that end in exclamations points indicate that they modify
# their argument.
@show arr = [5,4,6]  # => 3-element Array{Int64,1}: [5,4,6]
@show sort(arr)
@show arr;

arr = [5, 4, 6] = [5, 4, 6]
sort(arr) = [4, 5, 6]
arr = [5, 4, 6]


In [111]:
@show sort!(arr)
@show arr ;

sort!(arr) = [4, 5, 6]
arr = [4, 5, 6]


Note that when multiplying vectors and matrices, dimensions matter. For example, you can't multiply a vector by a vector:

In [115]:
b * b

MethodError: MethodError: no method matching *(::Vector{Int8}, ::Vector{Int8})

Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...)
   @ Base operators.jl:578
  *(!Matched::StridedMatrix{T}, ::StridedVector{S}) where {T<:Union{Float32, Float64, ComplexF32, ComplexF64}, S<:Real}
   @ LinearAlgebra /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/LinearAlgebra/src/matmul.jl:49
  *(::StridedVecOrMat, !Matched::LinearAlgebra.Adjoint{<:Any, <:LinearAlgebra.LQPackedQ})
   @ LinearAlgebra /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/LinearAlgebra/src/lq.jl:269
  ...


But multiplying transposes works:

In [116]:
b'

1×2 adjoint(::Vector{Int8}) with eltype Int8:
 4  5

In [119]:
@show b' * b    # i.e., inner product
@show b * b'    # i.e., outer product

b' * b = 41
b * b' = Int8[16 20; 20 25]


2×2 Matrix{Int8}:
 16  20
 20  25

#### Broadcasting
Element-by-element binary operations on arrays of different sizes.

In [120]:
a = [5,1,5.,1]; b = [2,3,4,5];

@show a .+ b
@show a .* b

@show convert.(Float32, [1, 2])
@show exp.(a) ;

a .+ b = [7.0, 4.0, 9.0, 6.0]
a .* b = [10.0, 3.0, 20.0, 5.0]
convert.(Float32, [1, 2]) = Float32[1.0, 2.0]
exp.(a) = [148.4131591025766, 2.718281828459045, 148.4131591025766, 2.718281828459045]


We can do linear algebra: (e.g., solve the linear system Ax = b):

In [112]:
x = A \ b

2-element Vector{Float64}:
 -3.0
  3.5

In [113]:
A * x

2-element Vector{Float64}:
 4.0
 5.0

In [114]:
A * x == b

true

### Tuples

Julia makes extensive use of a simple data structure called Tuples.  Tuples are immutable collections of values.

For example,

In [121]:
t = ("hello", 1.2, π)

("hello", 1.2, π)

In [122]:
typeof(t)

Tuple{String, Float64, Irrational{:π}}

Tuples can be accessed by index, similar to arrays,

In [123]:
t[2]

1.2

And can be "unpacked" like so,

In [124]:
a, b, c = t
@show a b c

a = "hello"
b = 1.2
c = π


π = 3.1415926535897...

In [125]:
# Easy to swap two values
d = 4; e = 5;
e, d = d, e  # => (5,4) 
@show d  # => 5
@show e ; # => 4

d = 5
e = 4


The values can also be given names, which is a convenient way of making light-weight data structures.

In [126]:
t = (word="hello", num=1.2, sym=:foo)

(word = "hello", num = 1.2, sym = :foo)

Then values can be accessed using a dot syntax,

In [127]:
t.word

"hello"

### Dictionaries

Similar to Python, Julia has native support for dictionaries.  Dictionaries provide a very generic way of mapping keys to values.  For example, a map of strings to integers.

In [8]:
d1 = Dict("A" => 1, "B" => 2, "D" => 4)

Dict{String, Int64} with 3 entries:
  "B" => 2
  "A" => 1
  "D" => 4

Looking up values uses the bracket syntax,

In [9]:
d1["B"]

2

Dictionaries can be nested

In [131]:
d2 = Dict("A" => 1, "B" => 2, "D" => Dict(:foo => 3, :bar => 4))

Dict{String, Any} with 3 entries:
  "B" => 2
  "A" => 1
  "D" => Dict(:bar=>4, :foo=>3)

In [134]:
# Get all keys
@show keys(d2)
@show haskey(d2, "A")     # => true
@show haskey(d2, 1);       # => false

keys(d2) = ["B", "A", "D"]
haskey(d2, "A") = true
haskey(d2, 1) = false


In [135]:
# Get all values
values(d2)

ValueIterator for a Dict{String, Any} with 3 entries. Values:
  2
  1
  Dict(:bar => 4, :foo => 3)

### Sets
Sets are used to represent collections of unordered, unique values

In [136]:

emptySet = Set()  # => Set(Any[])
# Initialize a set with values
filledSet = Set([1, 2, 2, 3, 4])  # => Set([4, 2, 3, 1])

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [137]:
# Add more values to a set
push!(filledSet, 5)  # => Set([4, 2, 3, 5, 1])

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [138]:
@show 2 in filledSet
@show 10 in filledSet

2 in filledSet = true
10 in filledSet = false


false

There are functions for set intersection, union, and difference.

In [139]:
filledSet = Set([1, 2, 2, 3, 4])            # => Set([4, 2, 3, 1])
otherSet = Set([3, 4, 5, 6])                # => Set([4, 3, 5, 6])
@show intersect(filledSet, otherSet)        # => Set([4, 3, 5])
@show union(filledSet, otherSet)            # => Set([4, 2, 3, 5, 6, 1])
@show setdiff(Set([1,2,3,4]),Set([2,3,5])); # => Set([4, 1])

intersect(filledSet, otherSet) = Set([4, 3])
union(filledSet, otherSet) = Set([5, 4, 6, 2, 3, 1])
setdiff(Set([1, 2, 3, 4]), Set([2, 3, 5])) = Set([4, 1])


### Dataframes

Tools for working with tabular data in Julia. (See [DataFrames.jl](https://github.com/JuliaData/DataFrames.jl/tree/main)).

You can create a DataFrame in many ways: using a `Constructor`, from a Julia `dict`, `NamedTuple`s, `matrix`, or by reading data from a CSV file:

In [140]:
using CSV
using DataFrames

df = DataFrame(A=1:3, B=5:7, fixed=1)   # constructor

3×3 DataFrame
 Row │ A      B      fixed 
     │ Int64  Int64  Int64 
─────┼─────────────────────
   1 │     1      5      1
   2 │     2      6      1
   3 │     3      7      1

In [141]:
dict = Dict(:customer_age => [15, 20, 25],
            :first_name => ["Rohit", "Rahul", "Akshat"])
df =  DataFrame(dict)   # from dictionary

3×2 DataFrame
 Row │ customer_age  first_name 
     │ Int64         String     
─────┼──────────────────────────
   1 │           15  Rohit
   2 │           20  Rahul
   3 │           25  Akshat

In [142]:
mat = [1 2 4 5; 15 58 69 41; 23 21 26 69]
header = ["a", "b", "c", "d"]
df = DataFrame(mat, header)     # from matrix

3×4 DataFrame
 Row │ a      b      c      d     
     │ Int64  Int64  Int64  Int64 
─────┼────────────────────────────
   1 │     1      2      4      5
   2 │    15     58     69     41
   3 │    23     21     26     69

In [143]:
df = DataFrame(CSV.File("../Notebooks/anatomy_data/solar_battery_data.csv"))     # from CSV

96×5 DataFrame
 Row │ T      Hour   Interval  Price    Solar   
     │ Int64  Int64  Int64     Float64  Float64 
─────┼──────────────────────────────────────────
   1 │     1      1         1    12.77      0.0
   2 │     2      1         2    11.82      0.0
   3 │     3      1         3    12.39      0.0
   4 │     4      1         4    10.17      0.0
   5 │     5      2         1     5.86      0.0
   6 │     6      2         2     2.69      0.0
   7 │     7      2         3     1.46      0.0
   8 │     8      2         4     1.41      0.0
  ⋮  │   ⋮      ⋮       ⋮         ⋮        ⋮
  90 │    90     23         2    16.16      0.0
  91 │    91     23         3    15.3       0.0
  92 │    92     23         4    15.18      0.0
  93 │    93     24         1    13.61      0.0
  94 │    94     24         2    11.89      0.0
  95 │    95     24         3    14.23      0.0
  96 │    96     24         4    14.09      0.0
                                 81 rows omitted

To extract the columns of a `DataFrame` directly (i.e. without copying) you can use one of the following syntaxes: `df.T`, `df."T"`, `df[!, :T]` or `df[!, "T"]` (a copy is made when usign `df[:,T]`):

In [222]:
df."T"

96-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
  ⋮
 88
 89
 90
 91
 92
 93
 94
 95
 96

You can obtain a vector of column names of the data frame as `Strings` using the `names` function:

In [223]:
names(df)

5-element Vector{String}:
 "T"
 "Hour"
 "Interval"
 "Price"
 "Solar"

If you were interested in element types of the columns, you can use the `eachcol` function to iterate over the columns, and `eltype` function to get the desired output:

In [224]:
eltype.(eachcol(df))

5-element Vector{DataType}:
 Int64
 Int64
 Int64
 Float64
 Float64

Other useful function:

In [225]:
df_copy = copy(df)
empty_df = empty(df)    # returns an empty dataframe with same column names and types, but with zero rows
empty!(df_copy)  # remove all rows from df_copy in-place

@show size(df)  # dataframe dimensions
@show size(df, 1)   # dataframe dimension along first axis
@show size(df, 2)   # dataframe dimension along second axis
@show nrow(df)  # number of rows
@show ncol(df)  # number of columns
describe(df)  # get basis statistcs of data

size(df) = (96, 5)
size(df, 1) = 96
size(df, 2) = 5
nrow(df) = 96
ncol(df) = 5
describe(df) = 5×7 DataFrame
 Row │ variable  mean     min    median   max    nmissing  eltype
     │ Symbol    Float64  Real   Float64  Real   Int64     DataType
─────┼──────────────────────────────────────────────────────────────
   1 │ T         48.5      1       48.5   96            0  Int64
   2 │ Hour      12.5      1       12.5   24            0  Int64
   3 │ Interval   2.5      1        2.5    4            0  Int64
   4 │ Price     15.4707  -1.19    13.97  77.85         0  Float64
   5 │ Solar     16.8261   0.0      0.0   50.0          0  Float64


5×7 DataFrame
 Row │ variable  mean     min    median   max    nmissing  eltype   
     │ Symbol    Float64  Real   Float64  Real   Int64     DataType 
─────┼──────────────────────────────────────────────────────────────
   1 │ T         48.5      1       48.5   96            0  Int64
   2 │ Hour      12.5      1       12.5   24            0  Int64
   3 │ Interval   2.5      1        2.5    4            0  Int64
   4 │ Price     15.4707  -1.19    13.97  77.85         0  Float64
   5 │ Solar     16.8261   0.0      0.0   50.0          0  Float64

Visualization:

In [226]:
first(df,6) # first 6 rows

6×5 DataFrame
 Row │ T      Hour   Interval  Price    Solar   
     │ Int64  Int64  Int64     Float64  Float64 
─────┼──────────────────────────────────────────
   1 │     1      1         1    12.77      0.0
   2 │     2      1         2    11.82      0.0
   3 │     3      1         3    12.39      0.0
   4 │     4      1         4    10.17      0.0
   5 │     5      2         1     5.86      0.0
   6 │     6      2         2     2.69      0.0

In [227]:
last(df,6)  # last 6 rows

6×5 DataFrame
 Row │ T      Hour   Interval  Price    Solar   
     │ Int64  Int64  Int64     Float64  Float64 
─────┼──────────────────────────────────────────
   1 │    91     23         3    15.3       0.0
   2 │    92     23         4    15.18      0.0
   3 │    93     24         1    13.61      0.0
   4 │    94     24         2    11.89      0.0
   5 │    95     24         3    14.23      0.0
   6 │    96     24         4    14.09      0.0

Indexing a `DataFrame`:

In [37]:
df2 = df[1:2, [1,3]]

2×2 DataFrame
 Row │ A      fixed 
     │ Int64  Int64 
─────┼──────────────
   1 │     1      1
   2 │     2      1

In [229]:
df1 = df[1:3, 1:4]

3×4 DataFrame
 Row │ T      Hour   Interval  Price   
     │ Int64  Int64  Int64     Float64 
─────┼─────────────────────────────────
   1 │     1      1         1    12.77
   2 │     2      1         2    11.82
   3 │     3      1         3    12.39

Changing the data stored in a `DataFrame`:

In [230]:
new_val = [3,4,5]
df1.Hour = new_val
df1

3×4 DataFrame
 Row │ T      Hour   Interval  Price   
     │ Int64  Int64  Int64     Float64 
─────┼─────────────────────────────────
   1 │     1      3         1    12.77
   2 │     2      4         2    11.82
   3 │     3      5         3    12.39

### Control-flow: Loops

#### For-Each Loops

Julia has native support for for-each style loops with the syntax `for <value> in <collection> end`.
Iterable types include `Range`, `Array`, `Set`, `Dict`, and `AbstractString`.

In [231]:
for i in 1:5
    println(i)
end

1
2
3
4
5


In [232]:
for i in [1.2, 2.3, 3.4, 4.5, 5.6]
    println(i)
end

1.2
2.3
3.4
4.5
5.6


This for-each loop also works with dictionaries.

In [233]:
for (key, value) in Dict("A" => 1, "B" => 2.5, "D" => 2 - 3im)
    println("$key: $value")
end

B: 2.5
A: 1
D: 2 - 3im


In [14]:
# Unnested for loop
for i in 1:4, j = 1:5
    println("i: $i\t j: $j\t i*j: $i*$j")
end

i: 1	 j: 1	 i*j: 1*1
i: 1	 j: 2	 i*j: 1*2
i: 1	 j: 3	 i*j: 1*3
i: 1	 j: 4	 i*j: 1*4
i: 1	 j: 5	 i*j: 1*5
i: 2	 j: 1	 i*j: 2*1
i: 2	 j: 2	 i*j: 2*2
i: 2	 j: 3	 i*j: 2*3
i: 2	 j: 4	 i*j: 2*4
i: 2	 j: 5	 i*j: 2*5
i: 3	 j: 1	 i*j: 3*1
i: 3	 j: 2	 i*j: 3*2
i: 3	 j: 3	 i*j: 3*3
i: 3	 j: 4	 i*j: 3*4
i: 3	 j: 5	 i*j: 3*5
i: 4	 j: 1	 i*j: 4*1
i: 4	 j: 2	 i*j: 4*2
i: 4	 j: 3	 i*j: 4*3
i: 4	 j: 4	 i*j: 4*4
i: 4	 j: 5	 i*j: 4*5


Note that in contrast to vector languages like Matlab and R, loops do not result in a significant performance degradation in Julia.

#### While-loop

In [235]:
x = 0
while x < 4
    println(x)
    x += 1  # Shorthand for in place increment: x = x + 1
end

0
1
2
3


### Control Flow - Conditionals
 
Julia control flow is similar to Matlab, using the keywords `if-elseif-else-end`, and the logical operators `||` and `&&` for *or* and *and* respectively. 


In [15]:
for i in 0:3:15
    if i < 5 
        println("$(i) is less than 5")
    elseif i < 10
        println("$(i) is less than 10")
    else
        if i == 10
            println("the value is 10")
        else
            println("$(i) is bigger than 10")
        end
    end
end

0 is less than 5
3 is less than 5
6 is less than 10
9 is less than 10
12 is bigger than 10
15 is bigger than 10


### Comprehensions

Similar to languages like Haskell and Python, Julia supports the use of simple loops in the construction of arrays and dictionaries, called comprehenions.

A list of increasing integers,

In [237]:
[i for i in 1:5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

Matrices can be built by including multiple indices,

In [238]:
[i*j for i in 1:5, j in 5:10]

5×6 Matrix{Int64}:
  5   6   7   8   9  10
 10  12  14  16  18  20
 15  18  21  24  27  30
 20  24  28  32  36  40
 25  30  35  40  45  50

A similar syntax can be used for building dictionaries

In [16]:
Dict("$i" => i for i in 1:10 if i%2 == 1)

Dict{String, Int64} with 5 entries:
  "1" => 1
  "5" => 5
  "7" => 7
  "9" => 9
  "3" => 3

Conditional statements can be used to filter out some values,

In [239]:
[i for i in 1:10 if i%2 == 1]

5-element Vector{Int64}:
 1
 3
 5
 7
 9

### Functions

A simple function is defined as follows,

In [241]:
function print_hello()
    println("hello")
end
print_hello()

hello


Arguments can be added to a function,

In [242]:
function print_it(x)
    println(x)
end

print_it("hello")
print_it(1.234)

hello
1.234


In [62]:
function add(x, y)
    println("x is $x and y is $y")

    # Functions return the value of their last statement
    return x + y
end

add(5, 6)

x is 5 and y is 6


11

As with variables, Unicode can also be used for function names:

In [17]:
∑(x,y) = x + y

∑(2, 3)

5

The keyword `return` is used to specify the return values of a function.

In [63]:
function mult(x; y=2.0)
    return x * y
end
mult(4.0)

8.0

In [64]:
mult(4.0, y=5.0)

20.0

Compact assignment of functions ("assignment form"):

In [65]:
f_add(x, y) = x + y  # => f_add (generic function with 1 method)
f_add(3, 4)  # => 7

7

Function can also return multiple values as tuple

In [248]:
fn(x, y) = x + y, x - y # => fn (generic function with 1 method)
fn(3, 4)  # => (7, -1)

(7, -1)

You can define functions with optional positional arguments

In [74]:
function defaults(a, b, x=5, y=6)
    return "$a $b and $x $y"
end

@show defaults(3,5)
@show defaults(3,5,2)
@show defaults(3,5,2,5) ;

defaults(3, 5) = "3 5 and 5 6"
defaults(3, 5, 2) = "3 5 and 2 6"
defaults(3, 5, 2, 5) = "3 5 and 2 5"


Optional keyword arguments are also possible 

In [75]:
function print_it(x; prefix="value:")
    println("$(prefix) $x")
end
print_it(1.234)
print_it(1.234, prefix="Result:")

value: 1.234
val: 1.234


There are `built-in` higher order functions, like `map`, `filter`, which apply a function to a `collection`:

In [19]:
my_fun(x) = x + 10
map(my_fun, [1,2,3])  # => [11, 12, 13]

3-element Vector{Int64}:
 11
 12
 13

In [253]:
filter(x -> x > 5, [3, 4, 5, 6, 7])  # => [6, 7]

2-element Vector{Int64}:
 6
 7

Functions can be assigned to variables, passed into functions, returned from a functions (i.e., they are **first-class** objects in Julia) 

In [76]:
function create_adder(x)
    adder = function (y)
        return x + y
    end
    return adder
end

param_add = create_adder(10)
param_add(3)

13

The ... is called a `splat`. It can be used in a function call, and in a function definition, where it will splat an Array or Tuple's contents into the argument list (automatically assigned as multiple function arguments).

In [18]:
y = (5, 6)  # => (5,6)
@show add(y...)  # this is equivalent to add(5,6)

multiply(x...) = only(map(prod,x))
@show multiply(y);

UndefVarError: UndefVarError: `add` not defined

### Mutable vs immutable objects

Some types in Julia are *mutable*, which means you can change the values inside them. A good example is an array. You can modify the contents of an array without having to make a new array.

In contrast, types like `Float64` are *immutable*. You can't modify the contents of a `Float64`.

This is something to be aware of when passing types into functions. For example:

In [254]:
function mutability_example(mutable_type::Vector{Int}, immutable_type::Int)
    mutable_type[1] += 1
    immutable_type += 1
    return
end

mutable_type = [1, 2, 3]
immutable_type = 1

mutability_example(mutable_type, immutable_type)

println("mutable_type: $(mutable_type)")
println("immutable_type: $(immutable_type)")

mutable_type: [2, 2, 3]
immutable_type: 1


Because `Vector{Int}` is a mutable type, modifying the variable inside the function changed the value outside of the function. In constrast, the change to `immutable_type` didn't modify the value outside the function.

You can check mutability with the `isimmutable` function.

In [255]:
@show isimmutable([1, 2, 3])
@show isimmutable(1);

isimmutable([1, 2, 3]) = false
isimmutable(1) = true


## Let's code 

### Exercise 1

Reverse an array in two different ways (one can be done using the function `reverse`).

In [ ]:
a = [1,2,3,4,5]
# write your solution here

<details>
<summary>Solution</summary>

```julia
a[end:-1:1] #faster
```
```julia
reverse(a)
```
```julia
reverse!(a) #inplace
```

### Exercise 2

Let `x` be a vector. Write code that prints an error if `x` is empty (has zero elements)

In [ ]:
# write your solution here

<details>
<summary>Solution</summary>

You can do it like this:
```
length(x) == 0 && println("x is empty")
```

*Extra*: typically in such case one would use the `isempty` function and throw
an exception instead of just printing information (here I assume that `x` was
passed as an argument to the function):
```
isempty(x) && throw(ArgumentError("x is not allowed to be empty"))
```

### Exercise 3

Compute the maximum difference between two numbers in an array.

In [ ]:
a = [2, 6, 8, 32, 16]
b = [2.1, 1.2, 3.5, 3.2]
# write your solution here

<details>
<summary>Solution</summary>

You can define is as follows:
```julia
fun(x::AbstractVector) = maximum(x) - minimum(x)
```

or as follows:

```julia
function fun2(x::AbstractVector)
    lo, hi = extrema(x)
    return hi - lo
end
```
Note that these two functions will work with vectors of any elements that are ordered and support subtraction (they do not have to be numbers).

### Exercise 4
Define two functions to solve the first two exercises. 

In [ ]:
# write your function here

### Exercise 5

Define a function that returns `true` if an input string is palindrome, `false` otherwise.

In [ ]:
# write your function here

<details>
<summary>Solution</summary>

```julia
function is_palindrome(string_var)
    return string_var == string_var[end:-1:1]
end
```

```bash
a = "Princeton"
b = "HANNAH"

@show is_palindrome(a)
@show is_palindrome(b)
```

### Exercise 6
Define a function that counts how many times a letter is present in an input string and returns a dict of `"letter" => count`

In [ ]:
# write your function here

<details>
<summary>Solution</summary>

```julia
function histogram_letters(string_var)  
    ret = Dict()
    for k in string_var
        ret[k] = get!(ret,k,0) + 1 # 0 è il defalt return value if the key is not present
    end
    return ret 
end
```

```bash
a = "Princeton"
@show (histogram_letters(a))
```

### Exercise 7
Define a function to calculate the volume of a sphere

In [1]:
# write your function here

<details>
<summary>Solution</summary>

```julia
function sphere_vol(r)
    return 4/3*pi*r^3
end
```
Or, more succinctly
```julia
sphere_vol(r) = 4/3*pi*r^3
```

### Exercise 8
1. Write a function that calculates the Fibonacci numbers for positive arguments  

2. Using the BenchmarkTools.jl package measure runtime of this function for n ranging from 1 to 20.

In [5]:
# write your function here

<details>
<summary>Solution</summary>

```julia
fib(n) = n < 3 ? 1 : fib(n-1) + fib(n-2)
```

```bash
julia> using BenchmarkTools

julia> for i in 1:40
           print(i, " ")
           @btime fib($i)
       end
```
Notice that execution time for number `n` is roughly sum of execution times for numbers `n-1` and `n-2`.

*Extra* (better version):
```bash
julia> const fib_dict = Dict{Int, Int}()
function fib2(n)
           haskey(fib_dict, n) && return fib_dict[n]
           fib_n = n < 3 ? 1 : fib2(n-1) + fib2(n-2)
           fib_dict[n] = fib_n
           return fib_n
       end
```

### Exercise 9
- Create a matrix of shape 2x3 containing numbers from 1 to 6 (fill the matrix columnwise with consecutive numbers).   

- Next calculate sum, mean and standard deviation of each row and each column of this matrix (Hint: you can use the Statistics package).

In [ ]:
# write your solution here

<details>
<summary>Solution</summary>

```bash
julia> using Statistics
julia> mat = [1 3 5
              2 4 6]

julia> sum(mat, dims=1)

julia> sum(mat, dims=2)

julia> mean(mat, dims=1)

julia> mean(mat, dims=2)

julia> std(mat, dims=1)

julia> std(mat, dims=2)
```

### Exercise 10
Read data stored in a gzip-compressed file `example8.csv.gz` into a `DataFrame` called `df`.

In [ ]:
# write your solution here

<details>
<summary>Solution</summary>

```julia
using CSV
using DataFrames

df = CSV.read("example8.csv.gz", DataFrame)
```

### Exercise 11
Get number of rows, columns, column names and summary statistics of the `df` data frame from exercise 10.

In [ ]:
# write your solution here

<details>
<summary>Solution</summary>

```julia
julia> nrow(df)
4
```
```julia
julia> ncol(df)
2
```
```julia
julia> names(df)
2-element Vector{String}:
 "number"
 "square"
 ```
```julia
julia> describe(df)
2×7 DataFrame
 Row │ variable  mean     min    median   max    nmissing  eltype
     │ Symbol    Float64  Int64  Float64  Int64  Int64     DataType
─────┼──────────────────────────────────────────────────────────────
   1 │ number       2.5       1      2.5      4         0  Int64
   2 │ square       7.75      2      6.5     16         0  Int64
```


### Exercise 12
Add a column to `df` data frame with label "name_string" containing string representation of numbers in column number, i.e. ["one", "two", "three", "four"].

In [ ]:
# write your solution here

<details>
<summary>Solution</summary>

```bash
julia> df."name string" = ["one", "two", "three", "four"]
4-element Vector{String}:
 "one"
 "two"
 "three"
 "four"
```

```bash
julia> df
4×3 DataFrame
 Row │ number  square  name string
     │ Int64   Int64   String
─────┼─────────────────────────────
   1 │      1       2  one
   2 │      2       4  two
   3 │      3       9  three
   4 │      4      16  four
```

### Exercise 13
Check if `df` contains column `square2`.

In [ ]:
# write your solution here

<details>
<summary>Solution</summary>


```bash
hasproperty(df, :square2)
```

### Exercise 14
Extract column number from `df` and empty it.

In [152]:
# write your solution here

<details>
<summary>Solution</summary>

```bash
julia> empty!(df[:, :number])
Int64[]
```

Note: that you must not do `empty!(df[!, :number])` nor `empty!(df.number)` as it would corrupt the `df` data frame (these operations do non-copying extraction of a column from a data frame as opposed to `df[:, :number]` which makes a copy). For more details [DataFrames](https://github.com/JuliaData/DataFrames.jl).

### Exercise 15

Write a function that calculates a sum of absolute values of values stored in an array passed to it.

In [ ]:
a = [1,-3, 2., 4,2.]
# write your solution here


<details>
<summary>Solution</summary>

```
sumabs(x) = sum(abs, x)
```

### Exercise 16

Write a function that swaps first and last element in an array in place.

In [ ]:
a = [2, 1, 2.3, 6.1, -1.6, -3.3]
# write your solution here

<details>
<summary>Solution</summary>

This can be written for example as:

```julia
function swap!(x)
    f = x[1]
    x[1] = x[end]
    x[end] = f
    return x
end
```

Extra A more advanced way to write this function would be:
```julia
function swap!(x)
    if length(x) > 1
        x[begin], x[end] = x[end], x[begin]
    end
    return x
end
```

### Exercise 17

- Write a loop in global scope that calculates the sum of cubes of numbers from 1 to 10^6.   

- Next use the sum function to perform the same computation.   

What is the difference in timing of these operations? (Hint: use @time macro. See [link](https://docs.julialang.org/en/v1/manual/performance-tips/#Measure-performance-with-[@time](@ref)-and-pay-attention-to-memory-allocation))

In [ ]:
# write your solution here

<details>
<summary>Solution</summary>

Version in global scope:

```julia
s = 0
@time for i in 1:10^6
  global s += i^3
end
```

Version with a function using a sum function:

```julia
sum3(n) = sum(x -> x^3, 1:n)
```

```julia
@time sum3(10^6)
```

Version with sum function in global scope:

```julia
@time sum(x -> x^3, 1:10^6)
```

### Exercise 18
Using the `@btime` macro benchmark the time of calculating the sum of one million random floats. (Include `BenchmarkTools` to use @btime macro).

In [ ]:
# write your solution here

<details>
<summary>Solution</summary>

```bash
julia> using BenchmarkTools
julia> @btime sum($(rand(10^6))
```
Note that the following:

```bash
julia> @btime sum(rand(10^6))
```
would be an incorrect timing as you would also measure the time of generating of the vector.

Alternatively you can write:

```julia
julia> x = rand(10^6);
julia> @btime sum($x)
```

### Exercize 19

Define a function that accepts any Integer except Bool and returns the passed value. If `Bool` is passed an error should be thrown.

In [ ]:
# write your solution here

<details>
<summary>Solution</summary>

We check subtypes of Integer:

```julia
julia> subtypes(Integer)
3-element Vector{Any}:
 Bool
 Signed
 Unsigned
```

The first way to write such a function is then:

```julia
fun1(i::Union{Signed, Unsigned}) = i
```

and now we have:
```bash
julia> fun1(1)
1
julia> fun1(true)
ERROR: MethodError: no method matching fun1(::Bool)
```

The second way is:

```julia
fun2(i::Integer) = i
fun2(::Bool) = throw(ArgumentError("Bool is not supported"))
```

and now you have:

```bash
julia> fun2(1)
1

julia> fun2(true)
ERROR: ArgumentError: Bool is not supported
```